language: node_js
node_js:
- '6'
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "fyDKCwb/EbKqlFLp4qJKBz56sJHoP1DAx/xSeP9VeqnOG7Img/boHqInIZbUWj2SEsFvmNm6i17HGVE0IY11gdUU83qZnD4baRYIyLDaR6wfTfJEtF2LibsIeUPOA69WKR4oBMlLeurY8/Y/htMUSuH85ZMu+Gk3rXozJA1faz9gvke3gQQrKvGSfBBPAce3ktZq1hoK081A0GEbSakCS7YKCzJtj0EWieUXy5mo6MDMlUeF+dkmLRJlqAvNK2gBphZpd695hWEHMJTQ4fSA75KtsYp/CqJ6mT7ys7jmWttQPCE05E4AiEUFCdnUAgJqEYm+/fkGpraVnitaEwydN5qxnA7gJCBiTtChA6218AzfBVotw/x3WN0DxJYDULd8xcD4VkMkMwc5M6eOJ2jTcUs3DfOvH7vIDgH72/C76N0CKOO8CuOiWCLbUQ0Daz/Nfc/RBjXOqVYNNbUb2QtV2kXFKvTKHt9Z9I/drMPvpFTl2Z3WkbdYGIu13zdt4LHEQZhh75Imo2XLvr7bdZfMYK8MSQyCYepK6RQYlKBnHqRpRDEvn3szdXmpCz3LPZqCISaLHGIeVmMH9Hi29zeGsQDO6JTHV6Gcv8DPgYAy6bKmU+imhLQRt/kkZ/rNX9WxBLpUcbcRyaCz11qChm77UAjYTH1h4B2i0hIeTD/ASiI="
